#include <Arduino.h>

// Increase loopTask stack (default is ~8KB)
SET_LOOP_TASK_STACK_SIZE(16 * 1024);  // 16KB

#include <Wire.h>
#include <Adafruit_MPU6050.h>
#include <Adafruit_Sensor.h>
#include "model.h"   // generated by micromlgen

Eloquent::ML::Port::XGBClassifier model;
Adafruit_MPU6050 mpu;

// Flex pins
const int flexPins[5] = {49, 23, 22, 21, 20};

// Sampling / windowing
const int SAMPLE_HZ = 50;
const uint32_t DT_MS = 1000 / SAMPLE_HZ;

const int WIN = 50;      // 1.0s window
const int STEP = 10;     // infer every 0.2s (10 samples)

// Ring buffer: 5 flex + 6 imu = 11 channels
float buf[WIN][11];
int idx = 0, filled = 0, stepCount = 0;

// "Detect once" logic
int lastPred = -1;         // last raw prediction
int sameCount = 0;         // consecutive repeats
int lockedPred = -1;       // last announced prediction
uint32_t lockTime = 0;

const int STABLE_N = 4;              // need 4 same preds in a row (~0.8s)
const uint32_t COOLDOWN_MS = 1500;   // don't trigger again too fast

const char* labelName(int id) {
  switch (id) {
    case 0: return "assalamualaikum";
    case 1: return "kayf_haluk";
    case 2: return "mahowa_asmk";
    default: return "unknown";
  }
}

// Compute mean/std/min/max for each of 11 channels directly from the ring buffer.
// Output features: 11 * 4 = 44
void compute_features_ring(float out[44]) {
  // idx points to next write position => oldest sample
  for (int c = 0; c < 11; c++) {
    float sum = 0, sum2 = 0;
    float mn = 1e9, mx = -1e9;

    for (int i = 0; i < WIN; i++) {
      int bi = (idx + i) % WIN;   // oldest -> newest
      float v = buf[bi][c];
      sum += v;
      sum2 += v * v;
      if (v < mn) mn = v;
      if (v > mx) mx = v;
    }

    float mean = sum / WIN;
    float var  = (sum2 / WIN) - mean * mean;
    float std  = (var > 0) ? sqrtf(var) : 0;

    out[c + 0 * 11] = mean;
    out[c + 1 * 11] = std;
    out[c + 2 * 11] = mn;
    out[c + 3 * 11] = mx;
  }
}

void setup() {
  Serial.begin(115200);
  delay(300);

  Wire.begin(7, 8);
  if (!mpu.begin()) {
    Serial.println("ERR: MPU not found");
    while (1) delay(100);
  }

  mpu.setAccelerometerRange(MPU6050_RANGE_8_G);
  mpu.setGyroRange(MPU6050_RANGE_250_DEG);

  Serial.println("Inference READY");
}

void loop() {
  static uint32_t last = 0;
  uint32_t now = millis();
  if (now - last < DT_MS) return;
  last = now;

  // Read flex
  float f[5];
  for (int i = 0; i < 5; i++) f[i] = (float)analogRead(flexPins[i]);

  // Read IMU
  sensors_event_t a, g, temp;
  mpu.getEvent(&a, &g, &temp);

  // Pack sample
  float x[11] = {
    f[0], f[1], f[2], f[3], f[4],
    a.acceleration.x, a.acceleration.y, a.acceleration.z,
    g.gyro.x, g.gyro.y, g.gyro.z
  };

  // Push into ring buffer
  for (int c = 0; c < 11; c++) buf[idx][c] = x[c];
  idx = (idx + 1) % WIN;
  if (filled < WIN) filled++;
  if (filled < WIN) return;

  // Infer every STEP samples
  stepCount++;
  if (stepCount < STEP) return;
  stepCount = 0;

  // Compute features without allocating big arrays in loop()
  static float feats[44];
  compute_features_ring(feats);

  int pred = model.predict(feats);

  // Stability tracking
  if (pred == lastPred) sameCount++;
  else {
    lastPred = pred;
    sameCount = 1;
  }

  // Trigger once when stable, with cooldown
  uint32_t t = millis();
  bool cooldownOver = (t - lockTime) > COOLDOWN_MS;

  if (sameCount >= STABLE_N && pred != lockedPred && cooldownOver) {
    lockedPred = pred;
    lockTime = t;

    Serial.print("DETECTED ONCE: ");
    Serial.print(pred);
    Serial.print(" => ");
    Serial.println(labelName(pred));
  }
}